# This file was autogenerated by the 'packer hcl2_upgrade' command. We
# recommend double checking that everything is correct before going forward. We
# also recommend treating this file as disposable. The HCL2 blocks in this
# file can be moved to other files. For example, the variable blocks could be
# moved to their own 'variables.pkr.hcl' file, etc. Those files need to be
# suffixed with '.pkr.hcl' to be visible to Packer. To use multiple files at
# once they also need to be in the same folder. 'packer inspect folder/'
# will describe to you what is in that folder.
#
# Avoid mixing go templating calls ( for example ```{{ upper(`string`) }}``` )
# and HCL2 calls (for example '${ var.string_value_example }' ). They won't be
# executed together and the outcome will be unknown.
#
# All generated input variables will be of 'string' type as this is how Packer JSON
# views them; you can change their type later on. Read the variables type
# constraints documentation
# https://www.packer.io/docs/templates/hcl_templates/variables#type-constraints for more info.
##############################################################################################
variable "winrm_username" {
    type          = string
    description   = "default winrm username used by packer to log into windows image"
}

variable "winrm_password" {
    type          = string
    description   = "default winrm username used by packer to log into windows image"
    sensitive     = true
}

variable "ssh_username" {
    type          = string
    description   = "default ssh username used by packer to log into linux image"
}

variable "ssh_password" {
    type          = string
    description   = "default ssh password used by packer to log into linux image"
    sensitive     = true
}

variable "vcenter_server" {
    type          = string
    description   = "HomeLab vCenter Server"
}

variable "datacenter" {
    type          = string
    description   = "HomeLab vCenter Server Datacenter"
}

variable "cluster" {
    type          = string
    description   = "HomeLab vCenter Server Cluster"
}

variable "host" {
    type          = string
    description   = "HomeLab vCenter Server Host to build images"
}

variable "datastore" {
    type          = string
    description   = "HomeLab vCenter Server vSAN Datastore to build images"
}

variable "folder" {
    type          = string
    description   = "HomeLab vCenter Server target folder for image"
}

variable "vcenter_username" {
    type          = string
    sensitive     = true
    description   = "HomeLab vCenter Server Username"
}

variable "vcenter_password" {
    type          = string
    sensitive     = true
    description   = "HomeLab vCenter Server Password"
}

# source blocks are analogous to the "builders" in json templates. They are used
# in build blocks. A build block runs provisioners and post-processors on a
# source. Read the documentation for source blocks here:
# https://www.packer.io/docs/templates/hcl_templates/blocks/source
source "vsphere-iso" "centos-83" {
  ############ VM Config ############
  CPUs                 = 1
  RAM                  = 1024
  RAM_reserve_all      = true
  disk_controller_type = ["pvscsi"]
  storage {
    disk_size             = 20000
    disk_thin_provisioned = true
  }
  network_adapters {
    network      = "VM Network"
    network_card = "vmxnet3"
  }
  guest_os_type        = "centos8_64Guest"
  insecure_connection  = true

  ############ Boot Config ############
  boot_wait            = "10s"
  http_directory       = "http/centos8"
#  output_directory     = "output/"
  boot_command         = ["<wait10><up><tab><wait>",
                          " text ks=http://{{ .HTTPIP }}:{{ .HTTPPort }}/centos-8-ks.cfg",
                          "<enter><wait>"] 
#  floppy_files         = ["${path.root}/preseed.cfg"]
  iso_urls             = ["http://mirror.cs.pitt.edu/centos/8.3.2011/isos/x86_64/CentOS-8.3.2011-x86_64-dvd1.iso"]
  iso_checksum         = "aaf9d4b3071c16dbbda01dfe06085e5d0fdac76df323e3bbe87cce4318052247"

  
  ############ User Config ############
  ssh_username           = "${var.ssh_username}"
  ssh_password           = "${var.ssh_password}"
  ssh_pty                = true
  ssh_timeout            = "20m"
  ssh_handshake_attempts = "200"

  ############ vSphere Config ############
  vcenter_server = "${var.vcenter_server}"
  datacenter     = "${var.datacenter}"
  cluster        = "${var.cluster}"
  datastore      = "${var.datastore}"
  folder         = "${var.folder}"
  vm_name        = "centos-83-vsp-pkr-{{ timestamp }}"
  username       = "${var.vcenter_username}"
  password       = "${var.vcenter_password}"
}

# a build block invokes sources and runs provisioning steps on them. The
# documentation for build blocks can be found here:
# https://www.packer.io/docs/templates/hcl_templates/blocks/build
build {
  sources = ["source.vsphere-iso.centos-83"]

  provisioner "shell" {
    inline = ["ls /",
              "/bin/yum install epel-release -y",
              "/bin/yum install cloud-init -y",
              "/bin/yum update -y ",
              "cloud-init clean"
             ]
  }
}
